### ISSUE TITLE
Will we need user accounts?

### ISSUE THREAD

**Issue by BoyanP** [CMPUT301W15T01/Team1Project#18]
Will we need user accounts? for approvers and people with claims.

**Comment by aylmao** [comment]
"You'll need the concept of a user, who is uniquely identifiable by name, but for the current user stories, you don't need to get heavy with user IDs, passwords. user authentication, or approval rights.

As a user, I might make a claim (be a claimant), and I might approve claim(s) (be an approver) for other people (not including me)."
