### ISSUE TITLE
Who added a second test folder??!

### ISSUE THREAD

**Issue by Cdingram** [CMPUT301W15T01/Team1Project#75]

**Comment by Joduro** [comment]
looks like that was probably me, just pretend that its not there

**Comment by Joduro** [comment]
or no, some of those things in there are not mine but some are so I have no idea

**Comment by Joduro** [comment]
It looks like the name of the folder was changed somehow, I'll change it back

**Comment by Cdingram** [comment]
Ok I thought it was a duplicate I was sweating

**Comment by Joduro** [comment]
...and... a merge happened while I was changing the folder name and NOW there is duplicate folders on my end. We should probably just leave the name change for now as its too bothersome to fix it.

**Comment by Cdingram** [comment]
Make sure the duplicate doesn't find it's way into our master though. If we have two test folders and people are changing both individually that would be a major headache

**Comment by Joduro** [comment]
yeah, I purged my entire folder and re-cloned it to make sure that it never gets out and all evidence of it's existence is lost.
