### ISSUE TITLE
doc/mockup/.DS_Store  is empty 

### ISSUE THREAD

**Issue by aylmao** [CMPUT301W15T01/Team1Project#88]
https://github.com/CMPUT301W15T01/Team1Project/blob/master/doc/mockup/.DS_Store 
the file is empty

**Comment by yotomyoto** [comment]
no it's not it contains all this:
Bud1	esbwspblobimagesbwspblob¯bplist00Ÿ	



]ShowStatusBar[ShowSidebar[ShowPathbar[ShowToolbar[ShowTabView_ContainerShowSidebar\WindowBounds\SidebarWidth_PreviewPaneVisibility			_{{720, 37}, {720, 840}}™)5AMYp}ä¢£§•¶ß®¬ƒ≈imageslg1ScompntimagesmoDDdutc—≈øimagesmodDdutc—≈øimagesph1Scomp‡ @Ä @Ä @Ä @E	DSDB `Ä @Ä @Ä @

but it's just some random file that accidentally got added it can be removed
