### ISSUE TITLE
claimant vs approver

### ISSUE THREAD

**Issue by aylmao** [CMPUT301W15T01/Team1Project#95]
should we be asserting user.type() for test cases that want as a claimant i can do ...
and as an approver i can do ...

**Comment by Cdingram** [comment]
We definitely could. For mine I just assumed that if they were in the claimant side of the app they had selected the user type.

**Comment by yotomyoto** [comment]
This seems like it would be really awkward to make meaningful since for testcases you're pretty much setting up the entire environment for the test to take place, not generally testing an actual running instance of the app.
